{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;\f1\fnil\fcharset0 Menlo-Bold;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue255;\red128\green0\blue128;\red251\green2\blue7;
}
{\*\expandedcolortbl;;\cssrgb\c1680\c19835\c100000;\cssrgb\c57919\c12801\c57269;\cssrgb\c100000\c14913\c0;
}
\paperw11900\paperh16840\margl1440\margr1440\vieww21520\viewh7240\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 ##############################################################################################\
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0
\cf0 \
dhavalbagal@Dhavals-MacBook-Air dns % 
\f1\b python3 mydig.py \cf2 amazon.com\cf0  \cf3 A\cf0  --dnssec
\f0\b0 \
Traceback (most recent call last):\
  File "/Users/dhavalbagal/Desktop/SBU/FCN/dns/mydig.py", line 16, in <module>\
    response = resolver.resolve(args.server, args.type)\
  File "/Users/dhavalbagal/Desktop/SBU/FCN/dns/dnssecresolver.py", line 318, in resolve\
    self._check_trust(hostname, main_response, redirection_history)\
  File "/Users/dhavalbagal/Desktop/SBU/FCN/dns/dnssecresolver.py", line 168, in _check_trust\
    raise NoDNSSECSupportError(zone_name)\

\f1\b \cf4 dns_exceptions.NoDNSSECSupportError\cf0 : DNSSEC not enabled for 'amazon.com.'
\f0\b0 \
\
##############################################################################################\
\
dhavalbagal@Dhavals-MacBook-Air dns % 
\f1\b python3 mydig.py \cf2 example.com\cf0  \cf3 A\cf0  --dnssec
\f0\b0 \
QUESTION SECTION:\
example.com.		IN	A\
\
ANSWER SECTION:\
93.184.216.34            \
\
Query time: 1230 msec\
WHEN: Thu Sep 23 10:06:13 2021\
\
MSG SIZE rcvd: 62\
\
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0
\cf0 ##############################################################################################\
\
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0
\cf0 dhavalbagal@Dhavals-MacBook-Air dns % 
\f1\b python3 mydig.py \cf2 verisigninc.com\cf0  \cf3 A\cf0  --dnssec
\f0\b0 \
QUESTION SECTION:\
verisigninc.com.		IN	A\
\
ANSWER SECTION:\
209.131.162.45\
69.58.187.40            \
\
Query time: 4331 msec\
WHEN: Thu Sep 23 10:06:23 2021\
\
MSG SIZE rcvd: 76\
\
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0
\cf0 ##############################################################################################\
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0
\cf0 \
dhavalbagal@Dhavals-MacBook-Air dns % 
\f1\b python3 mydig.py \cf2 dnssec-failed.org\cf0  \cf3 A\cf0  --dnssec
\f0\b0 \
Traceback (most recent call last):\
  File "/Users/dhavalbagal/Desktop/SBU/FCN/dns/mydig.py", line 16, in <module>\
    response = resolver.resolve(args.server, args.type)\
  File "/Users/dhavalbagal/Desktop/SBU/FCN/dns/dnssecresolver.py", line 318, in resolve\
    self._check_trust(hostname, main_response, redirection_history)\
  File "/Users/dhavalbagal/Desktop/SBU/FCN/dns/dnssecresolver.py", line 187, in _check_trust\
    raise KSKVerificationError(zone_name)\

\f1\b \cf4 dns_exceptions.KSKVerificationError\cf0 : KSK verification for 'dnssec-failed.org.' failed.\
\
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\b0 \cf0 ##############################################################################################}